services:
  elog-frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-/api}
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-elog.wizzgeeks.com}
    ports:
      - "7205:7205"
    networks:
      - shared-app-network
    restart: unless-stopped

networks:
  shared-app-network:
    external: true
